---
- name: Add MySQL Package
  apt: deb={{ mysql_deb }}
  become: yes

- name: Install MySQL
  apt: name={{ item }} state=present update_cache=yes
  become: yes
  register: mysql_installed
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb
