---
- name: Add Percona Package
  apt: deb={{ percona_deb }}
  become: yes

- name: Install Percona Server
  apt: name={{ item }} state=present update_cache=yes
  become: yes
  register: mysql_installed
  with_items:
    - percona-server-server-{{ percona_version }}
    - libmysqlclient-dev
    - "{{ 'python3-mysqldb' if ansible_python.version.major == 3 else 'python-mysqldb' }}"
