---
- name: Add MySQL Package
  apt: deb={{ mysql_deb }} update_cache=yes
  become: yes

- name: Install MySQL
  apt: name={{ item }} state=present
  become: yes
  register: mysql_install
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb

- name: Install Percona Toolkit
  apt: package=percona-toolkit state=present
  become: yes

# - name: Create Configuration File
#   template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
#   become: yes
#   notify: Restart MySQL

- include: lockdown.yml
  when: mysql_install | changed
