---
- name: Add MariaDB APT Key
  apt_key: keyserver=keyserver.ubuntu.com id={{ mariadb_apt_key[ansible_distribution_release] }} state=present
  become: yes

- name: Add MariaDB APT Repository
  apt_repository: repo="{{ item }} {{ ansible_distribution_release }} main" state=present
  become: yes
  with_items:
    - deb {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu
    - deb-src {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu

- name: Install MariaDB
  apt: name={{ item }} state=present update_cache=yes
  become: yes
  register: mysql_installed
  with_items:
    - mariadb-server
    - libmariadb-dev
    - "{{ 'python3-mysqldb' if ansible_python.version.major == 3 else 'python-mysqldb' }}"
