---
- name: Add MariaDB APT Key
  apt_key: keyserver=keyserver.ubuntu.com id={{ mariadb_apt_key_id }} state=present
  become: yes

- name: Add MariaDB APT Repository
  apt_repository: repo="{{ item }} {{ ansible_distribution_release }} main" state=present
  become: yes
  with_items:
    - deb {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu
    - deb-src {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu

- name: Install MariaDB
  apt: name={{ item }} state=present update_cache=yes
  become: yes
  register: mariadb_install
  with_items:
    - mariadb-server
    - libmariadb-dev
    - python-mysqldb

- name: Install Percona Toolkit
  apt: package=percona-toolkit state=present
  become: yes

- include: lockdown.yml
  when: mariadb_install | changed
