---
- include: install_mysql.yml
  static: no
  when: install_mysql

- include: install_mariadb.yml
  static: no
  when: install_mariadb

- include: install_percona.yml
  static: no
  when: install_percona

- block:
  - name: Install Percona Toolkit
    apt: package=percona-toolkit state=present
    become: yes

  - name: Delete Default Configs
    file: name=/etc/mysql/{{ item }} state=absent
    become: yes
    notify: Restart MySQL
    with_items:
      - conf.d/mariadb.cnf
      - conf.d/mysqld_safe_syslog.cnf
      - mysql.conf.d/mysqld.cnf
      - percona-server.conf.d/mysqld.cnf
      - percona-server.conf.d/mysqld_safe.cnf

  - name: Copy Config Files
    template: src={{ item.src }} dest=/etc/mysql/{{ item.dest }}
    become: yes
    when: item.when
    notify: Restart MySQL
    with_items:
      - { src: my.cnf.j2,          dest: my.cnf,                 when: yes }
      - { src: mysqld_safe.cnf.j2, dest: conf.d/mysqld_safe.cnf, when: yes }
      - { src: mysqld.cnf.j2,      dest: conf.d/mysqld.cnf,      when: yes }
      - { src: client.cnf.j2,      dest: conf.d/client.cnf,      when: yes }
      - { src: mysqldump.cnf.j2,   dest: conf.d/mysqldump.cnf,   when: yes }
      - { src: isamchk.cnf.j2,     dest: conf.d/isamchk.cnf,     when: yes }
      - { src: innodb.cnf.j2,      dest: conf.d/innodb.cnf,      when: yes }
      - { src: passwords.cnf.j2,   dest: conf.d/passwords.cnf,   when: "{{ env_name != 'dev' }}" }

  - include: lockdown.yml
    when:
      - mysql_installed is defined
      - mysql_installed is changed
  when: install_mysql or install_mariadb or install_percona

- include: user.yml
  static: no
  when: new_db_name is defined or (new_db_user is defined and new_db_pass is defined)
